### PR TITLE
Remove deadlock of 500s after transmit error

### PR DESCRIPTION
**Pull request by mkreisl**
This issue bugged me since a couple of month
See also Pulse-Eight/libcec#94

### CODE REVIEW

**Comment by opdenkamp** [comment]
but what you are trying to do (using cec-client and libCEC at the same time) is not supported, and will be blocked again in one of the next versions before we get questions about "weird" things happening when people try this

**Comment by opdenkamp** [comment]
there's an api command in kodi to do what you were trying to do btw, check builtins.cpp. using that will work without issues

**Comment by mkreisl** [comment]
Oh great, than I can't used the XBian function to turn off TV after Screensaver :-(

**Comment by mkreisl** [comment]
But anyway, use of sleep at this position will wait Seconds instead of Milliseconds

**Comment by mkreisl** [comment]
> there's an api command in kodi to do what you were trying to do btw, check builtins.cpp. using that will work without issues

Yeah, I played a little bit with this but unfortunately `./kodi-send.py --action="CECStandby"` doesn't turn of my TV, just writes a message to the log `May 22 18:54:28 T:3034255360   DEBUG: ToggleDeviceState - putting CEC device on standby...`
Tested it with Kodi v15.0b2 and libcec 3.0.0 on my RPi1

**Comment by opdenkamp** [comment]
then this has to get fixed too ;-)

**Comment by CurlyMoo** [comment]
> then this has to get fixed too ;-)

**too** as in also removing the ridiculous timeout of 500 sec?

**Comment by opdenkamp** [comment]
_too_ as in fixing the typo/oversight in https://github.com/mkreisl/libcec/commit/f9c4a2de412487b78c333dc21d9b7e41a5fe69e3 and the bug in Kodi that's preventing the command from being sent. register that on trac with a full debug log please.

**Comment by CurlyMoo** [comment]
So what about that `sleep(500)` instead of a gracefull:

```
static int terminate = 0;

function gracefulSleep(s) {
    int i = 0;
    while(i < s && terminate == 0) {
         sleep(1);
         i++;
    }
}
```

**Comment by mkreisl** [comment]
I'm not sure if this is a bug of feature.
`./kodi-send.py --action="CECStandby"` works if `Devices to power off during shutdown` is set to `TV`. However, I would expect that this command should work in all cases
And yes, I could set this option but if I stop Kodi,  Kodi does not turn on TV again if `Devices to power on during startup` is set to `TV` on my system.

**Comment by opdenkamp** [comment]
@CurlyMoo `CEvent::Sleep()` can be cancelled, is platform independent (doesn't really matter in this specific class), yields to other threads, can handle waits < 1 second, and I can go on for a while why it should be used rather than your snippet ;-)

@mkreisl right, that's a bug, it shouldn't check that setting if the action is called explicitly via an api command

**Comment by CurlyMoo** [comment]
Yet you're rejecting this patch? Or am i interpreting it wrong?

**Comment by opdenkamp** [comment]
I guess you are, why would I reject a typo fix?

**Comment by opdenkamp** [comment]
> and will be blocked again in one of the next versions before we get questions about "weird" things happening when people try this

I meant that I'll probably prevent accessing libCEC by more than 1 process pretty soon, as we do with the USB-CEC, or at least some TVs will be confused by the resulting traffic on the line. Kodi's API command should be used instead, and fixed for those who've disabled automatic power up and standby in the settings.

**Comment by CurlyMoo** [comment]
I though these comments were about this patch while they weren't.

**Comment by mkreisl** [comment]
@opdenkamp final question: is there a way to power on again TV w/o pressing the power button at the remote control? At the moment I can't see a working solution
If I use the `CECToggleState` command, it floods the log with

```
May 22 20:46:21 T:2941133840   DEBUG: CecLogMessage - << 10:04
May 22 20:46:21 T:2941133840   DEBUG: Previous line repeats 1 times.
May 22 20:46:21 T:2941133840   DEBUG: CecLogMessage - failed to make 'Recorder 1' the active source. will retry later
```

until I turn on TV manually

**Comment by mkreisl** [comment]
So far with

> using that will work without issues

....

**Pull request merged**
